name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarQube:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Clonar el código fuente
      - name: Checkout Code
        uses: actions/checkout@v2

      # Paso 2: Detectar el lenguaje y configurar el análisis
      - name: Detect Language
        run: |
          if [ -f "pom.xml" ]; then
            echo "language=java" >> $GITHUB_ENV
          elif [ -f "package.json" ]; then
            echo "language=javascript" >> $GITHUB_ENV
          elif [ -f "requirements.txt" ] || ls *.py 1> /dev/null 2>&1; then
            echo "language=python" >> $GITHUB_ENV
          elif [ -f "Makefile" ] || ls *.c *.cpp 1> /dev/null 2>&1; then
            echo "language=cpp" >> $GITHUB_ENV
          elif [ -f "go.mod" ]; then
            echo "language=go" >> $GITHUB_ENV
          elif [ -f "composer.json" ]; then
            echo "language=php" >> $GITHUB_ENV
          elif ls *.csproj 1> /dev/null 2>&1; then
            echo "language=dotnet" >> $GITHUB_ENV
          else
            echo "language=unknown" >> $GITHUB_ENV
          fi

      # Paso 3: Ejecutar el análisis de SonarQube
      - name: Run SonarQube Scan and Save Report
        run: |
          case "$language" in
            java)
              mvn -B clean verify sonar:sonar -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONARQUBE_USER_TOKEN
              ;;
            javascript)
              npx sonarqube-scanner -Dsonar.projectKey=my-node-project -Dsonar.sources=src -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONARQUBE_USER_TOKEN
              ;;
            python)
              sonar-scanner -Dsonar.projectKey=my-python-project -Dsonar.sources=. -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONARQUBE_USER_TOKEN
              ;;
            cpp)
              build-wrapper-linux-x86-64 --out-dir bw-output make
              sonar-scanner -Dsonar.projectKey=my-cpp-project -Dsonar.sources=. -Dsonar.cfamily.build-wrapper-output=bw-output -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONARQUBE_USER_TOKEN
              ;;
            go)
              sonar-scanner -Dsonar.projectKey=my-go-project -Dsonar.sources=. -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONARQUBE_USER_TOKEN
              ;;
            php)
              sonar-scanner -Dsonar.projectKey=my-php-project -Dsonar.sources=. -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONARQUBE_USER_TOKEN
              ;;
            dotnet)
              dotnet build
              dotnet sonarscanner begin /k:"my-dotnet-project" /d:sonar.login=$SONARQUBE_USER_TOKEN /d:sonar.host.url=$SONAR_HOST_URL
              dotnet build
              dotnet sonarscanner end /d:sonar.login=$SONARQUBE_USER_TOKEN
              ;;
            *)
              echo "No supported language detected!"
              exit 1
              ;;
          esac

          # Descargar el informe en formato JSON desde la API de SonarQube
          curl -u $SONARQUBE_USER_TOKEN: -o sonar-report.json "$SONAR_HOST_URL/api/issues/search?componentKeys=my-project&ps=500"

      # Paso 4: Guardar el informe JSON directamente en el repositorio
      - name: Commit SonarQube Report to GitHub
        run: |
          git config --global user.name "0111100"
          git config --global user.email "alexpena3107@gmail.com"
          git checkout -b sonar-report
          mv sonar-report.json path/to/save/sonar-report.json
          git add path/to/save/sonar-report.json
          git commit -m "Add SonarQube report"
          git push --set-upstream origin sonar-report
